FROM registry.hub.docker.com/library/centos:7.9.2009
LABEL maintainer="Kristian Berg <kristian.berg@tietoevry.com>"
RUN yum install -y rpm-build rpmdevtools yum-utils && yum clean all
COPY rpmbuilder.sh /usr/bin/rpmbuilder
ENTRYPOINT ["/usr/bin/rpmbuilder"]
